# Generated by Django 3.2 on 2023-05-17 23:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.CharField(max_length=10, unique=True, verbose_name='RA')),
                ('data_expiracao', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de Expiracao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('descricao', models.TextField(default=None, max_length=500, verbose_name='Descricao')),
                ('periodo', models.CharField(choices=[('MATUTINO', 'MATUTINO'), ('NOTURNO', 'NOTURNO')], default='MATUTINO', max_length=20)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('ONLINE', 'ONLINE')], default='PRESENCIAL', max_length=20)),
                ('imagem', models.ImageField(blank=True, upload_to='imagens/')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='app.coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horaria')),
                ('curso', models.ManyToManyField(to='app.Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(choices=[('TURMA A', 'TURMA A'), ('TURMA B', 'TURMA B'), ('TURMA C', 'TURMA C'), ('TURMA D', 'TURMA D')], default=None, max_length=7, verbose_name='Turma')),
                ('semestre', models.CharField(choices=[('PRI-SEM', 'PRIMEIRO SEMESTRE'), ('SEG-SEM', 'SEGUNDO SEMESTRE'), ('TER-SEM', 'TERCEIRO SEMESTRE'), ('QUA-SEM', 'QUARTO SEMESTRE')], default='PRI-SEM', max_length=20)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='app.curso')),
                ('disciplina', models.ManyToManyField(to='app.Disciplina')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('disciplina', models.ManyToManyField(blank=True, to='app.Disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATV', 'Ativa'), ('Canc', 'Cancelada'), ('Trc', 'Trancada'), ('An', 'Em Analise'), ('SO', 'Solicitada')], default=None, max_length=4)),
                ('dt_inicio', models.DateField()),
                ('dt_final', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='app.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='app.curso')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='app.turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PRORROGADA', 'Prorrogada')], max_length=10)),
                ('atividade', models.CharField(choices=[('ATV1', 'ATV1'), ('ATV2', 'ATV2'), ('ATV3', 'ATV3'), ('ATV4', 'ATV4'), ('ATV5', 'ATV5')], default='ATV1', max_length=4, verbose_name='Atividade Complementar')),
                ('dt_inicio', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Inicio')),
                ('dt_fim', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data Fim')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='app.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='app.professor')),
            ],
            options={
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('turma', 'curso', 'semestre'), name='unique_turma'),
        ),
    ]
