# Generated by Django 3.2 on 2023-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disciplina_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.CharField(choices=[('PRIMEIRO SEMESTRE', 'PRIMEIRO SEMESTRE'), ('SEGUNDO SEMESTRE', 'SEGUNDO SEMESTRE'), ('TERCEIRO SEMESTRE', 'TERCEIRO SEMESTRE'), ('QUARTO SEMESTRE', 'QUARTO SEMESTRE')], default='PRIMEIRO SEMESTRE', max_length=20),
        ),
    ]
