# Generated by Django 3.2 on 2023-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_turma_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.CharField(choices=[('1° SEMESTRE', 'PRIMEIRO SEMESTRE'), ('2° SEMESTRE', 'SEGUNDO SEMESTRE'), ('3° SEMESTRE', 'TERCEIRO SEMESTRE'), ('4° SEMESTRE', 'QUARTO SEMESTRE')], default='1° SEMESTRE', max_length=20),
        ),
    ]
