# Generated by Django 3.2 on 2023-06-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_turma_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
    ]
