# Generated by Django 3.2 on 2023-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aluno_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='turma',
            field=models.ManyToManyField(blank=True, to='app.Turma'),
        ),
    ]
