# Generated by Django 3.2 on 2023-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_atividade_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='turma',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='app.Turma'),
        ),
    ]
