# Generated by Django 3.2 on 2023-06-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_atividade_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('resposta', models.TextField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ENt', 'Entregue'), ('COr', 'Corrigido'), ('PEn', 'Pendente')], default='PEn', max_length=3)),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dt_entrega', models.DateField()),
                ('dt_avaliacao', models.DateField()),
                ('observacao', models.TextField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='file')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.aluno')),
                ('atividade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.atividade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professor')),
            ],
            options={
                'verbose_name_plural': 'Entrega da Atividade',
            },
        ),
    ]
