# Generated by Django 3.2 on 2023-06-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_entregaatividade_dt_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaatividade',
            name='dt_avaliacao',
        ),
    ]
