# Generated by Django 3.2 on 2023-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_entregaatividade_dt_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregaatividade',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='entregaatividade',
            name='status',
            field=models.CharField(choices=[('ENT', 'Entregue'), ('COR', 'Corrigido'), ('PEN', 'Pendente')], default='PEN', max_length=3),
        ),
    ]
