# Generated by Django 3.2 on 2023-06-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230612_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.ManyToManyField(blank=True, related_name='professor', to='app.Disciplina'),
        ),
    ]
