# Generated by Django 3.2 on 2023-06-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_professor_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matricula', to='app.aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matricula', to='app.curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matricula', to='app.turma'),
        ),
    ]
