# Generated by Django 3.2 on 2023-10-12 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_aluno_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('dt_envio', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Data de envio')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professor')),
            ],
        ),
    ]
