# Generated by Django 3.2 on 2023-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20231015_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PRORROGADA', 'Prorrogada'), ('ENTREGUE', 'Entregue')], max_length=10),
        ),
    ]
