# Generated by Django 3.2 on 2023-10-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_atividade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PRORROGADA', 'Prorrogada')], max_length=10),
        ),
        migrations.AlterField(
            model_name='entregaatividade',
            name='atividade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='app.atividade'),
        ),
    ]
