# Generated by Django 3.2 on 2023-10-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20231015_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregaatividade',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='app.atividade'),
        ),
    ]
