# Generated by Django 3.2 on 2023-10-28 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_alter_entregaatividade_atividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='professor',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='assunto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='destinatario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='auth.user'),
            preserve_default=False,
        ),
    ]
