# Generated by Django 3.2 on 2023-11-02 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_auto_20231028_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
